version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd rec-react-app
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: rec-react-app/dist
  files:
    - '**/*'
